# Generated by Django 6.0.5 on 2026-05-21 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(help_text='e.g. CS-2021-001', max_length=20, unique=True)),
                ('department', models.CharField(choices=[('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('BBA', 'Business Administration'), ('MED', 'Medical'), ('LAW', 'Law'), ('OTHER', 'Other')], default='CS', max_length=10)),
                ('phone_number', models.CharField(help_text='e.g. +92-300-1234567', max_length=15)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='students/profile_pics/')),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True, help_text='Permanent home address')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Currently residing?')),
                ('room', models.ForeignKey(blank=True, help_text='The room this student is allocated to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='rooms.room')),
                ('user', models.OneToOneField(help_text='The login account linked to this student', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['roll_number'],
            },
        ),
    ]
