# Generated by Django 6.0.5 on 2026-05-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='e.g. 101 or B-204', max_length=10, unique=True)),
                ('floor', models.IntegerField(choices=[(0, 'Ground Floor'), (1, 'First Floor'), (2, 'Second Floor'), (3, 'Third Floor'), (4, 'Fourth Floor')], default=0)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single Occupancy'), ('DOUBLE', 'Double Occupancy'), ('TRIPLE', 'Triple Occupancy'), ('DORM', 'Dormitory (4+)')], default='DOUBLE', max_length=10)),
                ('capacity', models.PositiveIntegerField(default=2, help_text='Maximum number of students')),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('amenities', models.TextField(blank=True, help_text='e.g. WiFi, AC, Attached Bath')),
                ('is_active', models.BooleanField(default=True, help_text='Is this room currently usable?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_number'],
            },
        ),
    ]
