# Generated by Django 6.0.5 on 2026-05-21 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('ROOM', 'Room Rent'), ('FOOD', 'Food / Mess'), ('ELEC', 'Electricity'), ('WATER', 'Water'), ('LAUNDRY', 'Laundry'), ('OTHER', 'Other')], default='ROOM', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount due', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Fully Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='PENDING', max_length=10)),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('due_date', models.DateField(help_text='Payment deadline')),
                ('payment_date', models.DateField(blank=True, help_text='Date payment was received', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, help_text='Optional notes about this fee record')),
                ('student', models.ForeignKey(help_text='The student this fee is charged to', on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Record',
                'verbose_name_plural': 'Fee Records',
                'ordering': ['-year', '-month'],
                'unique_together': {('student', 'fee_type', 'month', 'year')},
            },
        ),
    ]
