# Generated by Django 6.0.5 on 2026-05-21 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complaint_text', models.TextField(help_text='Describe your issue in detail')),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Room Maintenance'), ('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('FOOD', 'Food / Mess'), ('CLEANLINESS', 'Cleanliness'), ('SECURITY', 'Security'), ('NOISE', 'Noise Complaint'), ('INTERNET', 'Internet / WiFi'), ('OTHER', 'Other')], default='OTHER', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Under Review'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('admin_response', models.TextField(blank=True, help_text='Admin notes or resolution message')),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='complaints/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='students.student')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
