# Generated by Django 6.0.5 on 2026-05-21 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.CharField(blank=True, max_length=15)),
                ('relation', models.CharField(choices=[('PARENT', 'Parent'), ('SIBLING', 'Brother/Sister'), ('RELATIVE', 'Relative'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('purpose', models.TextField(blank=True, help_text='Reason for visiting')),
                ('id_proof_type', models.CharField(choices=[('CNIC', 'CNIC / National ID'), ('PASSPORT', 'Passport'), ('DRIVING', 'Driving License'), ('STUDENT_ID', 'Student ID'), ('OTHER', 'Other')], default='CNIC', max_length=15)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, help_text='Leave blank if still inside', null=True)),
                ('approved_by', models.CharField(blank=True, help_text='Guard or admin name', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(help_text='The student being visited', on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='students.student')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ['-entry_time'],
            },
        ),
    ]
